### ISSUE TITLE
Use LaundryView's JSON API instead of BeautifulSoup

### ISSUE THREAD

**Issue by metheno** [pittcsc/PittAPI#102]
I found those two APIs from LaundryView. The first returns university data and the second returns room data.    
https://www.laundryview.com/api/c_room?loc=197    
https://www.laundryview.com/api/currentRoomData?school_desc_key=197&location=2430137

I'm new to Python but I guess that JSON would be a bit more efficient than BeautifulSoup?

**Comment by RitwikGupta** [comment]
Woah, yeah, these are brand new. Want to make a PR to use these instead?

**Comment by azharichenko** [comment]
I have found someone (@katelyn98) that will update the laundry API with the use of the APIs from Laundryview.
