### ISSUE TITLE
Jun-1980-jones:dev

### ISSUE THREAD

**Issue by Jun-1980-jones** [pittcsc/PittAPI#211]
Jun-1980-jones:dev

_Originally posted by @Jun-1980-jones in https://github.com/pittcsc/PittAPI/pull/210#pullrequestreview-2489692209_

**Comment by Jun-1980-jones** [comment]
> ```
>           Jun-1980-jones:dev
> ```
> 
> _Originally posted by @Jun-1980-jones in [#210 (review)](https://github.com/pittcsc/PittAPI/pull/210#pullrequestreview-2489692209)_

          Jun-1980-jones:dev

**Comment by timparenti** [comment]
There is no need to open a separate issue to have a PR reviewed.
